### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by antiprism** [giobauermeister/ads1115-linux-rpi#2]
Hi

Thanks for sharing your project. Could you please add a licence (e.g. MIT License), or indicate one here, as I would like to use your code.

Thanks

Adrian.

**Comment by giobauermeister** [comment]
Done: https://github.com/giobauermeister/ads1115-linux-rpi/commit/4a19e24ec78e7dfd50405fdc0acb4c8517f49d1b

**Comment by antiprism** [comment]
Thanks. In the end I used the kernel driver and libiio for my project

   https://github.com/antiprism/turnandrun

Adrian.
