### ISSUE TITLE
Works with Adafruit's ADS 1115 board, too

### ISSUE THREAD

**Issue by pktmterenceg** [giobauermeister/ads1115-linux-rpi#4]
Thank you so much for sharing this repository. I wanted to let you/everyone know that this library also works well with Adafruit's ADS1115 board, too. I really struggled to get that working in C (instead of the many Arduino or python examples) and this project helped get me to where I needed my code to be. Thank you!

**Comment by giobauermeister** [comment]
@pktmterenceg glad to hear that my project helped you!
